--- #YAML:1.0
name:               Sub-Op
version:            0.01
abstract:           Install subroutines as opcodes.
author:
    - Vincent Pit <perl@profvince.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::Depends:    0
    ExtUtils::MakeMaker:  0
build_requires:
    B::Hooks::EndOfScope:  0
    blib:                 0
    Cwd:                  0
    DynaLoader:           0
    ExtUtils::Depends:    0
    ExtUtils::MakeMaker:  0
    File::Spec:           0
    POSIX:                0
    Test::More:           0
    Variable::Magic:      0.39
requires:
    B::Hooks::EndOfScope:  0
    DynaLoader:           0
    perl:                 5.01
    Variable::Magic:      0.39
resources:
    bugtracker:  http://rt.cpan.org/NoAuth/ReportBug.html?Queue=Sub-Op
    homepage:    http://search.cpan.org/dist/Sub-Op/
    license:     http://dev.perl.org/licenses/
    repository:  http://git.profvince.com/?p=perl%2Fmodules%2FSub-Op.git
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
dynamic_config:     1
